hr:
  employees:
    default:
      percent: 5
    smart:
      limit1: 2.5
      limit2: 5
      limit3: 10
      percent1: 0
      percent2: 2
      percent3: 5
      percent4: 10
spring:
  profiles:
    active: smart
